MobileGaget/Areas/Admin/Controllers/PhoneController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MobileGadget.DataAccess.Repository.IRepository;
using MobileGadget.Model;
using MobileGadget.Model.ViewModels;
using MobileGadget.Model.ViewModels;
using MobileGaget.Utility;

namespace MobileGadgetWeb.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class PhoneController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _hostEnvironment;
    public PhoneController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
    {
        _unitOfWork = unitOfWork;
        _hostEnvironment = hostEnvironment;
    }

    public IActionResult Index()
    {

        return View();
    }

    //Get (Get what to create)
    public IActionResult Upsert(int? id)
    {
        PhoneVM PhoneVM = new()
        {
            Phone = new()
        };
        if (id == null || id == 0)
        {
            return View(PhoneVM);
        }
        else
        {
            //Update Product
            PhoneVM.Phone = _unitOfWork.Phone.GetFirstOrDefault(u => u.Id == id);
            return View(PhoneVM);
        }
        //return View();
    }
    //POST (Create it)
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(Phone phone, PhoneVM obj, IFormFile? file)
    {
        if (phone.OperatingSystem == phone.DisplayOrder.ToString())
        {
            ModelState.AddModelError("OperatingSystem", "The Display Order exactly match the OPeratingSystem");
        }
        if (ModelState.IsValid)
        {


            string wwwRootPath = _hostEnvironment.WebRootPath;

            if (file != null)
            {

                //creating file name
                string fileName = Guid.NewGuid().ToString();

                //uploading the file:the location the file go when uploaded
                var uploads = Path.Combine(wwwRootPath, @"Images\Phones");

                //file exension

                var extension = Path.GetExtension(file.FileName);

                //working on update
                //checking if file exist in the file , if exist we delete the file
                if (obj.Phone.ImageUrl != null)
                {
                    //getting the image old path
                    var oldImagePath = Path.Combine(wwwRootPath, obj.Phone.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                // copy the file to fileStream location
                using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    file.CopyTo(fileStreams);

                }
                obj.Phone.ImageUrl = @"\Images\Phones\" + fileName + extension;
            }
            if (obj.Phone.Id == 0)
            {
                _unitOfWork.Phone.Add(obj.Phone);
            }
            else
            {
                _unitOfWork.Phone.Update(obj.Phone);
            }
            _unitOfWork.Save();
            TempData["Success"] = "Create successful";
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    public IActionResult Details()
    {
        IEnumerable<Phone> phoneList = _unitOfWork.Phone.GetAll();
        return View(phoneList);
    }



    #region API CALLs
    [HttpGet]
    //To get what you want to delete
    public IActionResult GetAll()
    {
        var PhoneList = _unitOfWork.Phone.GetAll();
        return Json(new { data = PhoneList });
    }
    //Post 

    [HttpDelete]
    //To delete it
    public IActionResult Delete(int? id)
    {
        var obj = _unitOfWork.Phone.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return Json(new { success = false, message = "Error while deleteing" });
        }
        var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
        if (System.IO.File.Exists(oldImagePath))
        {
            System.IO.File.Delete(oldImagePath);
        }
        _unitOfWork.Phone.Remove(obj);
        _unitOfWork.Save();
        return Json(new { success = true, message = "Delete successful" });
    }
}
#endregion

MobileGaget/Areas/Admin/Controllers/TechnicianController.cs
using Microsoft.AspNetCore.Mvc;
using MobileGadget.DataAccess.Repository.IRepository;
using MobileGadget.Model;
using MobileGadget.Model.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using MobileGaget.Model.ViewModels;
using Microsoft.AspNetCore.Authorization;
using MobileGaget.Utility;

namespace MobileGadgetWeb.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]

public class TechnicianController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _hostEnvironment;
    public TechnicianController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
    {
        _unitOfWork = unitOfWork;
        _hostEnvironment = hostEnvironment;
    }

    public IActionResult Index()
    {
        return View();
    }

    //Get (Get what to create)
    public IActionResult Upsert(int? id)
    {
        TechnicianVM technicianVM = new()
        {
            Technician = new()
        };
        if (id == null || id == 0)
        {
            return View(technicianVM);
        }
        else
        {
            //Update Product
            technicianVM.Technician = _unitOfWork.Technician.GetFirstOrDefault(u => u.Id == id);
            return View(technicianVM);
        }
        //return View();
    }
    //POST (Create it)
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(TechnicianVM obj, IFormFile? file)
    {
        if (ModelState.IsValid)
        {


            string wwwRootPath = _hostEnvironment.WebRootPath;

            if (file != null)
            {

                //creating file name
                string fileName = Guid.NewGuid().ToString();

                //uploading the file:the location the file go when uploaded
                var uploads = Path.Combine(wwwRootPath, @"Images\Technician");

                //file exension

                var extension = Path.GetExtension(file.FileName);

                //working on update
                //checking if file exist in the file , if exist we delete the file
                if (obj.Technician.ImageUrl != null)
                {
                    //getting the image old path
                    var oldImagePath = Path.Combine(wwwRootPath, obj.Technician.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                // copy the file to fileStream location
                using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    file.CopyTo(fileStreams);

                }
                obj.Technician.ImageUrl = @"\Images\Technician\" + fileName + extension;
            }
            if (obj.Technician.Id == 0)
            {
                _unitOfWork.Technician.Add(obj.Technician);
            }
            else
            {
                _unitOfWork.Technician.Update(obj.Technician);
            }
            _unitOfWork.Save();
            TempData["Success"] = "Created successful";
            return RedirectToAction("Index");
        }
        return View(obj);

    }

    public IActionResult Details()
    {
        IEnumerable<Technician> TechList = _unitOfWork.Technician.GetAll();
        return View(TechList);
    }

    #region API CALLs
    [HttpGet]
    //To get what you want to delete
    public IActionResult GetAll()
    {
        var TechnicianList = _unitOfWork.Technician.GetAll();
        return Json(new { data = TechnicianList });
    }
    //Post 

    [HttpDelete]
    //To delete it
    public IActionResult Delete(int? id)
    {
        var obj = _unitOfWork.Technician.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return Json(new { success = false, message = "Error while deleteing" });
        }
        var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
        if (System.IO.File.Exists(oldImagePath))
        {
            System.IO.File.Delete(oldImagePath);
        }
        _unitOfWork.Technician.Remove(obj);
        _unitOfWork.Save();
        return Json(new { success = true, message = "Delete successful" });
    }
}
#endregion

MobileGaget/Areas/Admin/Views/Technician/Details.cshtml
@model IEnumerable<MobileGadget.Model.Technician>


<div class="row pb-4">
    @foreach (var technician in Model)
    {
        <div class="col-lg-3 col-md-6">
            <div class="row pb-6">
                <div class="col-12 p-1" style="border:1px solid #008cba; border-radius:5px">
                    <div class="card">
                        <img src="@technician.ImageUrl" class="card-img-top rounded" />
                        <div class="card-body">
                            <div class="pl-1">
                                <p class="card-title h5 text-primary">@technician.CompanyName</p>
                                <p class="card-title  text-info"> Email: <b>@technician.EmailAddress</b></p>
                                <p class="card-title  text-info"> Contact: <b>@technician.PhoneNumber</b></p>
                                 <p class="card-title  text-info"> State: <b>@technician.State</b></p>
                                <p class="card-title  text-info"> Address: <b>@technician.StreetAddress</b></p>

                                <a asp-controller="Technician" asp-action="Index" class="btn btn-secondary" style="width:150px">
                                    Back to List
                                </a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    }
</div>

MobileGaget/Areas/Admin/Views/Technician/Index.cshtml
@model IEnumerable<MobileGadget.Model.Technician>

<partial name="_Notification" />



<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary"></h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Technician" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-square"></i> &nbsp; Create new user
            </a>
        </div>
    </div>
</div>
<br />
<br />

<table id="tblData" class="table table-boardered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>Company Name</th>
            <th>Address</th>
            <th>State</th>
            <th>City</th>
            <th>Email Address</th>
            <th>Phone Number</th>

            <th></th>


        </tr>
    </thead>
</table>

@*@section Scripts{
            {
    <partial name="_ValidationScriptsPartial" />
        }
    }
*@
 @section Scripts{
    <script src="~/js/Technician.js"></script>
    }

MobileGaget/Areas/Admin/Views/Technician/Upsert.cshtml
@model MobileGadget.Model.ViewModels.TechnicianVM

<form method="post" asp-action="Upsert" enctype="multipart/form-data">
	<input asp-for="Technician.Id" hidden />
	<input asp-for="Technician.ImageUrl" hidden />

	<div class="row">
		<div class="col-10">
			<div class="border p-3 mt-4 row">
				<div class="col-12 pb-2">
					<h2 class="text-primary">@(Model.Technician.Id != 0 ? "Update" : "Create")  User</h2>
					<hr />
				</div>
				<div asp-validation-summary="All"></div>
				<div class="mb-3 text-primary">
					<label asp-for="Technician.CompanyName"></label>
					<input asp-for="Technician.CompanyName" class="form-control" />
					<span asp-validation-for="Technician.CompanyName" class="text-danger"></span>
				</div>
				
				<div class="mb-3 col-6">
					<label asp-for="Technician.EmailAddress"></label>
					<input asp-for="Technician.EmailAddress" class="form-control" />
					<span asp-validation-for="Technician.EmailAddress" class="text-danger"></span>
				</div>

				<div class="mb-3 col-6">
					<label asp-for="Technician.PhoneNumber"></label>
					<input asp-for="Technician.PhoneNumber" class="form-control" />
					<span asp-validation-for="Technician.PhoneNumber" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label asp-for="Technician.ImageUrl"></label>
					<input type="file" id="uploadBox" name="file" class="form-control" />
				</div>


				<div class="mb-3 col-6">
				<label asp-for="Technician.StreetAddress"></label>
				<input asp-for="Technician.StreetAddress" class="form-control" />
				<span asp-validation-for="Technician.StreetAddress" class="text-danger"></span>
			</div>



				<div class="mb-3 col-6">
					<label asp-for="Technician.State"></label>
					<input asp-for="Technician.State" class="form-control" />
					<span asp-validation-for="Technician.State" class="text-danger"></span>
				</div>


			<div class="mb-3 col-6">
				<label asp-for="Technician.City"></label>
				<input asp-for="Technician.City" class="form-control" />
				<span asp-validation-for="Technician.City" class="text-danger"></span>
			</div>




				<div class="mb-3 col-6">
					<label asp-for="Technician.PostalCode"></label>
				<input asp-for="Technician.PostalCode" class="form-control" />
				<span asp-validation-for="Technician.PostalCode" class="text-danger"></span>
				</div>
				
				
				

				
				<div class="col-12">
					@if (Model.Technician.Id != 0)
					{
						<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
					}
					else
					{
						<button type="submit" onclick="return ValidateInput()" class="btn btn-primary" style="width:150px">Create</button>
					}
					<a asp-controller="Phone" asp-action="Index" class="btn btn-secondary" style="width:150px">
						Back to List
					</a>
				</div>

			</div>
		</div>
		<div class="col-2 pt-4">
			<img src="@Model.Technician.ImageUrl"
				 width="100%" style="border-radius:5px; border:1px solid #bbb9b9" />
		</div>
	</div>







</form>
<script>
		
		function ValidateInput() {
			if (document.getElementById("uploadBox").value == "") {
				Swal.fire({
					icon: 'error',
					title: 'Oops...',
					text: 'Please upload an Image!',
				});
				return false;
			}
			return true;
		}
	</script>