MobileGaget/Areas/Admin/Controllers/BuyController.cs
using MobileGadget.DataAccess.Repository.IRepository;
using MobileGadget.Model;
using MobileGadget.Model.ViewModels;
using MobileGaget.Models;
using MobileGaget.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.Extensions.Options;
using MobileGadget.DataAccess.Repository.IRepository;
using MobileGadget.Model.ViewModels;
using MobileGaget.Model;
using MobileGaget.Utility;
using Stripe.Checkout;
using System.Security.Claims;
using MobileGadget.Model;
using Microsoft.AspNetCore.Identity.UI.Services;

namespace MobileGadgetWeb.Areas.Admin.Controllers;


[Area("Admin")]
//only signed in user can access the Package
[Authorize]
//Controller for retreving shoppingCart  item that has already been added
public class BuyController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    // To bind ShoppingCartVM and ShoppingCartVM when we post form(so we dont have to write in post method)
    [BindProperty]
    public ShoppingCartVM ShoppingCartVM { get; set; }
    public int OrderTotal { get; set; }
    private readonly IEmailSender _emailSender;

    public BuyController(IUnitOfWork unitOfWork, IEmailSender emailSender)
    {
        _unitOfWork = unitOfWork;
        _emailSender = emailSender;
    }
    //Add the shoppingCart items together with Application UserId in Index 
    public IActionResult Indexs()
    {
        var claimIdentity = (ClaimsIdentity)User.Identity;
        var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);

        ShoppingCartVM = new ShoppingCartVM()
        {
            BuyList = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value, includeProperties: "Product"),

            // Creating new instance for OrderHeader since we are using it insdie the ShoppingCartVM
            OrderHeader = new()
        };
        foreach (var cart in ShoppingCartVM.BuyList)
        {
            //get the price cart based on count
            cart.Price = GetPriceBasedOnQuantity(cart.Count, cart.Product.Price);
            //taking the total cart price
            ShoppingCartVM.OrderHeader.OrderTotal += cart.Price * cart.Count;
        }


        return View(ShoppingCartVM);

    }
    //Get method for summary page
    //Add the shoppingCart items together with Application UserId in Summary
    public IActionResult Summary()
    {
        var claimIdentity = (ClaimsIdentity)User.Identity;
        var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);

        ShoppingCartVM = new ShoppingCartVM()
        {
            BuyList = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value, includeProperties: "Product"),
            // Creating new instance for OrderHeader since we are using it insdie the ShoppingCartVM
            OrderHeader = new()

        };
        //Getting the ApplicationUser From OrderHeader
        ShoppingCartVM.OrderHeader.ApplicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(
               u => u.Id == claim.Value);

        //Assigning the ApplicationUser  to OrderHeader Properties


        ShoppingCartVM.OrderHeader.Name = ShoppingCartVM.OrderHeader.ApplicationUser.Name;
        ShoppingCartVM.OrderHeader.PhoneNumber = ShoppingCartVM.OrderHeader.ApplicationUser.PhoneNumber;
        ShoppingCartVM.OrderHeader.StreetAddress = ShoppingCartVM.OrderHeader.ApplicationUser.StreetAddress;
        ShoppingCartVM.OrderHeader.City = ShoppingCartVM.OrderHeader.ApplicationUser.City;
        ShoppingCartVM.OrderHeader.State = ShoppingCartVM.OrderHeader.ApplicationUser.State;
        ShoppingCartVM.OrderHeader.PostalCode = ShoppingCartVM.OrderHeader.ApplicationUser.PostalCode;


        foreach (var cart in ShoppingCartVM.BuyList)
        {
            //get the price cart based on count
            cart.Price = GetPriceBasedOnQuantity(cart.Count, cart.Product.Price);
            //taking the total cart price
            ShoppingCartVM.OrderHeader.OrderTotal += cart.Price * cart.Count;
        }
        return View("Summary");

    }

    //Post method for summary page
    //Add the shoppingCart items together with Application UserId in Summary
    [HttpPost]
    [ValidateAntiForgeryToken]
    [ActionName("Summary")]
    public IActionResult SummaryPOST(ShoppingCartVM obj)
    {
        var claimIdentity = (ClaimsIdentity)User.Identity;
        var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);


        ShoppingCartVM.BuyList = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value, includeProperties: "Product");

        // Populating the Details need  for Order Header
        //ShoppingCartVM.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
        //ShoppingCartVM.OrderHeader.OrderStatus = SD.StatusPending;
        ShoppingCartVM.OrderHeader.OrderDate = DateTime.Now;
        ShoppingCartVM.OrderHeader.ApplicationUserId = claim.Value;

        foreach (var cart in ShoppingCartVM.BuyList)
        {
            //get the price cart based on count
            cart.Price = GetPriceBasedOnQuantity(cart.Count, cart.Product.Price);
            //taking the total cart price
            ShoppingCartVM.OrderHeader.OrderTotal += cart.Price * cart.Count;
        }



        //Check if the it's companyUser and if it's companyUser implment the companyUser flow
        ApplicationUser applicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == claim.Value);

        if (applicationUser.TechnicianId.GetValueOrDefault() == 0)
        {
            ShoppingCartVM.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
            ShoppingCartVM.OrderHeader.OrderStatus = SD.StatusPending;
        }
        else
        {
            ShoppingCartVM.OrderHeader.PaymentStatus = SD.PaymentStatusDelayedPayment;
            ShoppingCartVM.OrderHeader.OrderStatus = SD.StatusApproved;
        }
        //Adding the pouplated details need  for Order Header to the DB
       
        _unitOfWork.OrderHeader.Add(ShoppingCartVM.OrderHeader);
        _unitOfWork.Save();
       





        //  Populating the Details need  for Order Details
        foreach (var cart in ShoppingCartVM.BuyList)
        {
            OrderDetail orderDetail = new()
            {
                ProductId = cart.ProductId,
                OrderId = ShoppingCartVM.OrderHeader.Id,
                Price = cart.Price,
                Count = cart.Count,
            };
            _unitOfWork.OrderDetail.Add(orderDetail);
            _unitOfWork.Save();
           
        }

        //Check if the it's companyUser and if it's companyUser implment the cstripe setting
        if (applicationUser.TechnicianId.GetValueOrDefault() == 0)
        {
            ///Stripe API setting

            var domain = "https://localhost:44301/";
            var options = new SessionCreateOptions
            {
                //Add new session for card payment and LineItems
                PaymentMethodTypes = new List<string>
            {
                "card",
            },
                LineItems = new List<SessionLineItemOptions>(),

                Mode = "payment",
                SuccessUrl = domain + $"admin/buy/OrderConfirmation?id={ShoppingCartVM.OrderHeader.Id}",
                CancelUrl = domain + $"admin/buy/index",
            };
            foreach (var item in ShoppingCartVM.BuyList)
            {

                //LineItems option represent all of the item we have in our shoppingcart
                var sessionLineItem = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long)(item.Price * 100),//20.00 -> 2000
                        Currency = "usd",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.Product.ProductName
                        },

                    },
                    Quantity = item.Count,
                };
                options.LineItems.Add(sessionLineItem);
            }

            var service = new SessionService();
            Session session = service.Create(options);
            _unitOfWork.OrderHeader.UpdateStripePaymentID(ShoppingCartVM.OrderHeader.Id, session.Id, session.PaymentIntentId);
            _unitOfWork.Save();
            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }
        else
        {
            return RedirectToAction("OrderConfirmation", "buy", new { id = ShoppingCartVM.OrderHeader.Id });
        }

        //Removing ShoppingCartVM.ListCart
        //_unitOfWork.ShoppingCart.RemoveRange(ShoppingCartVM.ListCart);
        //_unitOfWork.Save();
        //return RedirectToAction("Index", "Home");
    }
    public IActionResult OrderConfirmations(int id)
    {
        OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(u => u.Id == id, includeProperties: "ApplicationUser");
        if (orderHeader.PaymentStatus != SD.PaymentStatusDelayedPayment)
        {
            var service = new SessionService();
            Session session = service.Get(orderHeader.SessionId);
            //check the stripe payment status
            if (session.PaymentStatus.ToLower() == "paid")
            {
                _unitOfWork.OrderHeader.UpdateStripePaymentID(id, orderHeader.SessionId, session.PaymentIntentId);
                _unitOfWork.OrderHeader.UpdateStatus(id, SD.StatusApproved, SD.PaymentStatusApproved);
                _unitOfWork.Save();
            }
        }
        //Sending email after order has been made
        _emailSender.SendEmailAsync(orderHeader.ApplicationUser.Email, "New Order - Bulky Book", "<p>New Order Created</p>");
        //Removing ShoppingCartVM.ListCart
        List<ShoppingCart> shoppingCarts = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId

MobileGaget/Areas/Customer/Controllers/HomeController.cs
using MobileGadget.DataAccess.Repository.IRepository;
using MobileGadget.Model;
using MobileGaget.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MobileGadget.DataAccess.Repository.IRepository;
using MobileGadget.Model;
using MobileGaget.Models;
using System.Diagnostics;
using System.Security.Claims;
using MobileGadget.DataAccess.Repository;
using MobileGadget.Model;
using MobileGadget.Model;
using MobileGadget.DataAccess.Repository.IRepository;
using MobileGaget.Model.ViewModels;
using MobileGadget.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using MobileGaget.Utility;
//using Stripe;

namespace MobileGadget.Areas.Customer.Controllers;
[Area("Customer")]
//Controller for Adding ShopppingCart items(Product)
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IUnitOfWork _unitOfWork;
    private readonly ApplicationDbContext _dbContext;
    public HomeController(ILogger<HomeController> logger, IUnitOfWork unitOfWork, ApplicationDbContext dbContext)
    {
        _logger = logger;
        _unitOfWork = unitOfWork;
        _dbContext = dbContext;
    }

    public IActionResult Index()
    {
        //To get all the product as model in this controller and include properties of category and coverType on index page

        IEnumerable<Product> productList = _unitOfWork.Product.GetAll(includeProperties: "Phone,Laptop");
        return View(productList);
    }
    [HttpGet]
    public  async Task<IActionResult> Index(string SearchString)
    {
        ViewData["ProductFilter"] = SearchString;
        var ProductSearch = from u in _dbContext.products
                            select u;
        if (!string.IsNullOrEmpty(SearchString))
        {
            ProductSearch = ProductSearch.Where(b => b.ProductName.Contains(SearchString));
        }
        return View(await ProductSearch.AsNoTracking().ToListAsync());
    }

    //[HttpGet]
    //public async Task<IActionResult> Index(string SerachString)
    //{
    //    ViewData["ProductFilter"] = SerachString;
    //    var productSearch = from u in _dbContext.products
    //                        select u;
    //    if (!String.IsNullOrEmpty(SerachString))
    //    {
    //        productSearch = productSearch.Where(b => b.ProductName.Contains(SerachString));
    //    }
    //    return View(await productSearch.AsNoTracking().ToListAsync());
    //}

    public IActionResult Details(int productId)
    {
        ShoppingCart cartObj = new()
        {
            Count = 1,
            ProductId = productId,
            Product = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == productId, includeProperties: "Phone,Laptop")
        };
        return View(cartObj);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    //only authorize user(sign in user can access this postActionMethod)
    [Authorize]
    //Add the shoppingCart items together with Application UserId 
    public IActionResult Details(ShoppingCart shoppingCart)
    {
        var claimIdentity = (ClaimsIdentity)User.Identity;
        var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
        shoppingCart.ApplicationUserId = claim.Value;

        //Adding shoppingCart to the existing shoppingCart the use added earlier
        ShoppingCart cartFromDb = _unitOfWork.ShoppingCart.GetFirstOrDefault(
            u => u.ApplicationUserId == claim.Value && u.ProductId == shoppingCart.ProductId);

        if (cartFromDb == null)
        {
            _unitOfWork.ShoppingCart.Add(shoppingCart);
            _unitOfWork.Save();
            //Adding session to the shoppingCart
            HttpContext.Session.SetInt32(SD.SessionCart,
               _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).ToList().Count);
        }
        else
        {
            _unitOfWork.ShoppingCart.IncrementCount(cartFromDb, shoppingCart.Count);
        }
      
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MobileGaget/Areas/Customer/Views/Home/Details.cshtml
@using MobileGadget.Model
@model ShoppingCart



<form method="post">
    <input hidden asp-for="ProductId" />
    <div class="card  container pt-4">
        <div class="card-header bg-primary text-light ml-0  row ">
            <div class="col-12 col-md-6">
                <h1 class="text-white-50">@Model.Product.ProductName</h1>
            </div>
            <div class="col-12 col-md-6 text-end pt-4">
                <span class="badge bg-info pt-2" style="height:30px;">@Model.Product.Phone.OperatingSystem</span>
                <span class="badge bg-warning pt-2" style="height:30px;">@Model.Product.Laptop.OperatingSystem</span>
            </div>
        </div>
        <div class="card-body row container">
            <div class="container rounded p-2">
                <div class="row">
                    <div class="col-8 col-lg-8">

                        <div class="row text-center pl-2" style="color:maroon; font-weight:bold">
                            <div class="p-1 col-2 bg-light">
                                <div>Price</div>
                            </div>
                            <div class="p-1 col-2 bg-light">
                                <div>@Model.Product.Price.ToString("n")</div>
                            </div>
                            
                        </div>
                        <div class="row pl-2">
                            <p class="text-secondary">Product Description: <b>@Html.Raw(Model.Product.About)</b></p>
                        </div>
                      
                      
                    </div>
                    <div class="col-12 col-lg-3 offset-lg-1 text-center">
                        <img src="@Model.Product.ImageUrl" width="100%" class="rounded" />
                    </div>
                    <div class="row pl-2">
                            <div class="col-2 text-primary"><h4>Quantity</h4></div>
                        <div class="col-10"><input asp-for="Count" style="width:100px;" class="form-control   input-sm" /></div>
                        </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-12 col-md-2">
                    <a class="btn btn-success form-control " style="width:150px" asp-action="Index">Back to Home</a>
                </div>
                <div class="col-12 col-md-2">
                    <button type="submit" value="Add to Cart" class="btn btn-primary form-control" style="width:150px">Add to Cart</button>
                </div>
                <div class="col-12 col-md-2">
                    <button type="submit" value="Buy now" class="btn btn-danger form-control" style="width:150px">Buy now</button>
                   @* <a class="btn btn-danger form-control" asp-area="Admin" asp-controller="Buy" asp-action="Indexs">Buy now</a>
                       *@
                </div>
            </div>
        </div>
    </div>
</form>

MobileGaget/Areas/Customer/Views/Home/Index.cshtml
@model IEnumerable<MobileGadget.Model.Product>




<form asp-action="Index" method="get">

    <div class="input-group md-form form-control-sm form-2 pl-0">

        <label for="SearchString"></label>
        <input class="form-control my-0 py-1 red-border" type="search" placeholder="Search products" name="SearchString"
               aria-describedby="basic-addon1" value="@ViewData["ProductFilter"]" />
               <div class="input-group-append">
                   <span class="input-group-text red ligthen-3" id="basic-text1">
                <i class="bi bi-search"></i>
                   </span>

               </div>
        <input type="submit" value="Search" class="btn btn-primary" />

        <a asp-action="Index" class="btn btn-primary mx-4"> <i class="bi bi-bag-fill"></i> &nbsp; All product</a>

    </div>






    
</form>

<div class="row pb-4">
    @foreach (var product in Model)
    {
        
        <div class="col-lg-3 col-md-6 m-4">
            <div class="row pb-6">
                <div class="col-12 p-1" style="border:1px solid #008cba; border-radius:5px">
                    <div class="card">
                        <img src="@product.ImageUrl" class="card-img-top rounded" />
                        <div class="card-body">
                            <div class="pl-1">
                                <p class="card-title h5 text-primary">@product.ProductName</p>
                                <p class="card-title  text-info">  <b>@product.ProductModel</b></p>
                                <p class="card-title  text-info">BH: <b>@product.BatteryCapacity</b></p>
                                <p class="card-title  text-info"> space: <b>@product.Storage</b></p>
                                <p class="card-title  text-info">Price: <b>@product.Price.ToString("n")</b></p>
                                <div>
                                    <a asp-action="Details" class="btn btn-primary form-control" asp-route-productId="@product.Id">
                                        More Details
                                    </a>
                                </div>
                            </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>




                           
    }
    </div>