MobileGaget/Areas/Admin/Controllers/LaptopController.cs
using Microsoft.AspNetCore.Mvc;
using MobileGadget.DataAccess.Repository.IRepository;
using MobileGadget.Model;
using MobileGadget.Model.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;

using MobileGadget.Model.ViewModels;
using Microsoft.AspNetCore.Authorization;
using MobileGaget.Utility;

namespace MobileGadgetWeb.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class LaptopController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _hostEnvironment;
    public LaptopController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
    {
        _unitOfWork = unitOfWork;
        _hostEnvironment = hostEnvironment;
    }

    public IActionResult Index()
    {
        return View();
    }

    //Get (Get what to create)
    public IActionResult Upsert(int? id)
    {
        LaptopVM laptopVM = new()
        {
            Laptop = new()
        };
        if (id == null || id == 0)
        {
            return View(laptopVM);
        }
        else
        {
            //Update Product
            laptopVM.Laptop = _unitOfWork.Laptop.GetFirstOrDefault(u => u.Id == id);
            return View(laptopVM);
        }
        //return View();
    }
    //POST (Create it)
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(Laptop laptop, LaptopVM obj, IFormFile? file)
    {
        if (laptop.OperatingSystem == laptop.DisplayOrder.ToString())
        {
            ModelState.AddModelError("OperatingSystem", "The Display Order exactly match the OPeratingSystem");
        }
        if (ModelState.IsValid)
        {


            string wwwRootPath = _hostEnvironment.WebRootPath;

            if (file != null)
            {

                //creating file name
                string fileName = Guid.NewGuid().ToString();

                //uploading the file:the location the file go when uploaded
                var uploads = Path.Combine(wwwRootPath, @"Images\Laptops");

                //file exension

                var extension = Path.GetExtension(file.FileName);

                //working on update
                //checking if file exist in the file , if exist we delete the file
                if (obj.Laptop.ImageUrl != null)
                {
                    //getting the image old path
                    var oldImagePath = Path.Combine(wwwRootPath, obj.Laptop.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                // copy the file to fileStream location
                using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    file.CopyTo(fileStreams);

                }
                obj.Laptop.ImageUrl = @"\Images\Laptops\" + fileName + extension;
            }
            if (obj.Laptop.Id == 0)
            {
                _unitOfWork.Laptop.Add(obj.Laptop);
            }
            else
            {
                _unitOfWork.Laptop.Update(obj.Laptop);
            }
            _unitOfWork.Save();
            TempData["Success"] = "Create successful";
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    public IActionResult Details()
    {
        IEnumerable<Laptop> LaptopList = _unitOfWork.Laptop.GetAll();
        return View(LaptopList);
    }




    #region API CALLs
    [HttpGet]
    //To get what you want to delete
    public IActionResult GetAll()
    {
        var LaptopList = _unitOfWork.Laptop.GetAll();
        return Json(new { data = LaptopList });
    }
    //Post 

    [HttpDelete]
    //To delete it
    public IActionResult Delete(int? id)
    {
        var obj = _unitOfWork.Laptop.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return Json(new { success = false, message = "Error while deleteing" });
        }
        var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
        if (System.IO.File.Exists(oldImagePath))
        {
            System.IO.File.Delete(oldImagePath);
        }
        _unitOfWork.Laptop.Remove(obj);
        _unitOfWork.Save();
        return Json(new { success = true, message = "Delete successful" });
    }
}
#endregion

MobileGaget/Areas/Admin/Controllers/PhoneController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MobileGadget.DataAccess.Repository.IRepository;
using MobileGadget.Model;
using MobileGadget.Model.ViewModels;
using MobileGadget.Model.ViewModels;
using MobileGaget.Utility;

namespace MobileGadgetWeb.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class PhoneController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _hostEnvironment;
    public PhoneController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
    {
        _unitOfWork = unitOfWork;
        _hostEnvironment = hostEnvironment;
    }

    public IActionResult Index()
    {

        return View();
    }

    //Get (Get what to create)
    public IActionResult Upsert(int? id)
    {
        PhoneVM PhoneVM = new()
        {
            Phone = new()
        };
        if (id == null || id == 0)
        {
            return View(PhoneVM);
        }
        else
        {
            //Update Product
            PhoneVM.Phone = _unitOfWork.Phone.GetFirstOrDefault(u => u.Id == id);
            return View(PhoneVM);
        }
        //return View();
    }
    //POST (Create it)
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(Phone phone, PhoneVM obj, IFormFile? file)
    {
        if (phone.OperatingSystem == phone.DisplayOrder.ToString())
        {
            ModelState.AddModelError("OperatingSystem", "The Display Order exactly match the OPeratingSystem");
        }
        if (ModelState.IsValid)
        {


            string wwwRootPath = _hostEnvironment.WebRootPath;

            if (file != null)
            {

                //creating file name
                string fileName = Guid.NewGuid().ToString();

                //uploading the file:the location the file go when uploaded
                var uploads = Path.Combine(wwwRootPath, @"Images\Phones");

                //file exension

                var extension = Path.GetExtension(file.FileName);

                //working on update
                //checking if file exist in the file , if exist we delete the file
                if (obj.Phone.ImageUrl != null)
                {
                    //getting the image old path
                    var oldImagePath = Path.Combine(wwwRootPath, obj.Phone.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                // copy the file to fileStream location
                using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    file.CopyTo(fileStreams);

                }
                obj.Phone.ImageUrl = @"\Images\Phones\" + fileName + extension;
            }
            if (obj.Phone.Id == 0)
            {
                _unitOfWork.Phone.Add(obj.Phone);
            }
            else
            {
                _unitOfWork.Phone.Update(obj.Phone);
            }
            _unitOfWork.Save();
            TempData["Success"] = "Create successful";
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    public IActionResult Details()
    {
        IEnumerable<Phone> phoneList = _unitOfWork.Phone.GetAll();
        return View(phoneList);
    }



    #region API CALLs
    [HttpGet]
    //To get what you want to delete
    public IActionResult GetAll()
    {
        var PhoneList = _unitOfWork.Phone.GetAll();
        return Json(new { data = PhoneList });
    }
    //Post 

    [HttpDelete]
    //To delete it
    public IActionResult Delete(int? id)
    {
        var obj = _unitOfWork.Phone.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return Json(new { success = false, message = "Error while deleteing" });
        }
        var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
        if (System.IO.File.Exists(oldImagePath))
        {
            System.IO.File.Delete(oldImagePath);
        }
        _unitOfWork.Phone.Remove(obj);
        _unitOfWork.Save();
        return Json(new { success = true, message = "Delete successful" });
    }
}
#endregion

MobileGaget/Areas/Admin/Controllers/ProductController.cs
using MobileGaget.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.Extensions.DependencyInjection;
using MobileGadget.DataAccess.Repository.IRepository;
using MobileGadget.DataAccess;
using MobileGadget.DataAccess.Repository;

using MobileGadget.Model;
using MobileGaget.Model.ViewModels;
using IServiceScope = Microsoft.Extensions.DependencyInjection.IServiceScope;
using Microsoft.AspNetCore.Authorization;
using MobileGaget.Utility;

namespace BulkyBookWeb.Areas.Admin.Controllers;
[Area("Admin")]
// Controller with one method for create and update(Upsert) and API for delete
// Use for CRUD Operation
[Authorize(Roles = SD.Role_Admin)]
public class ProductController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _hostEnvironment;


    public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
    {
        _unitOfWork = unitOfWork;
        _hostEnvironment = hostEnvironment;
    }
    public IActionResult Index()
    {
        return View();
    }
    //Code for Create(create) in this controller
    public IActionResult Upsert(int? id)
    {

        ProductVM productVM = new()
        {



            Product = new(),


            PhoneList = _unitOfWork.Phone.GetAll().Select(i => new SelectListItem
            {

                Text = i.OperatingSystem,
                Value = i.Id.ToString()
            }),
            LapTopList = _unitOfWork.Laptop.GetAll().Select(i => new SelectListItem
            {
                Text = i.OperatingSystem,
                Value = i.Id.ToString()
            }),
        };



        if (id == null || id == 0)
        {
            // Create Product
            //ViewBag.CategoryList = CategoryList;
            //ViewData["CoverTypeList"] = CoverTypeList;
            return View(productVM);
        }

        else
        {
            //Update Product
            productVM.Product = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
            return View(productVM);
        }

    }
    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    //Code for Edit(Update) in this controller
    public IActionResult Upsert(ProductVM obj, IFormFile? file)
    {
        if (ModelState.IsValid)
        {


            string wwwRootPath = _hostEnvironment.WebRootPath;

            if (file != null)
            {

                //creating file name
                string fileName = Guid.NewGuid().ToString();

                //uploading the file:the location the file go when uploaded
                var uploads = Path.Combine(wwwRootPath, @"Images\Products");

                //file exension

                var extension = Path.GetExtension(file.FileName);

                //working on update
                //checking if file exist in the file , if exist we delete the file
                if (obj.Product.ImageUrl != null)
                {
                    //getting the image old path
                    var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                // copy the file to fileStream location
                using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    file.CopyTo(fileStreams);

                }
                obj.Product.ImageUrl = @"\Images\Products\" + fileName + extension;
            }
            if (obj.Product.Id == 0)
            {
                _unitOfWork.Product.Add(obj.Product);
            }
            else
            {
                _unitOfWork.Product.Update(obj.Product);
            }
            _unitOfWork.Save();
            TempData["Success"] = "Product created successfully";
            return RedirectToAction("Index");
        }
        return View(obj);

    }


    #region API CALLs
    [HttpGet]
    //To get what you want to delete
    public IActionResult GetAll()
    {
        var ProductList = _unitOfWork.Product.GetAll(includeProperties: "Phone,Laptop");
        return Json(new { data = ProductList });
    }
    //Post 

    [HttpDelete]
    //To delete it
    public IActionResult Delete(int? id)
    {
        var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return Json(new { success = false, message = "Error while deleteing" });
        }
        var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
        if (System.IO.File.Exists(oldImagePath))
        {
            System.IO.File.Delete(oldImagePath);
        }
        _unitOfWork.Product.Remove(obj);
        _unitOfWork.Save();
        return Json(new { success = true, message = "Delete successful" });
    }
    #endregion

}

MobileGaget/ViewComponents/ShoppingCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using MobileGaget.Utility;
using MobileGadget.DataAccess.Repository.IRepository;

namespace MobileGadget.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        //Getting the ShopingCart list
        private IUnitOfWork _unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        //Getting the User Session
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                if (HttpContext.Session.GetInt32(SD.SessionCart) != null)
                {
                    //return the count
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
                else
                {
                    //getting all the shoppingcart and counting it
                    HttpContext.Session.SetInt32(SD.SessionCart,
                       
                        _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).ToList().Count);
                    // return the count
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

MobileGaget/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@using MobileGaget.Utility

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MobileGaget</title>
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MobileGaget.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />

    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <div class="logo mx-4">
                    <a href="#">
                        <img src="~/Images/Products/Capture.png" />
                    </a>
                </div>

                @*<a class="navbar-brand" href="#">MobileGadget</a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">HOME</a>
                        </li>
                        @*<li class="nav-item">
                        </li>
                        <li class="nav-item">
                        </li>*@


                        @*<li class="nav-item">
                        <a class="nav-link" href="#">Pricing</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                        </li>*@
                        @*Makiing the drop down visilble only to Admin*@
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Management</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Phone" asp-action="Index">Mobile Phone</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Laptop" asp-action="Index">Laptop</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Technician" asp-action="Index">Technician</a>
                                    <div class="dropdown-divider"></div>
                                   
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>

                                
                                    @*<a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>*@

                                </div>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">
                                MANAGE ORDER
                            </a>
                        </li>
                     
                            
                        

                       
                    </ul>
                    <partial name="_LoginPartial" />
                    @* <form class="d-flex">
                    <input class="form-control me-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>*@
                </div>
            </>
        </nav>
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
        <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BulkyBookWeb</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
        <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">

        </li>
        <li class="nav-item">
        </li>
        </ul>
        </div>
        </div>
        </nav>*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
   @* <script src="https://cdn.tiny.cloud/1/c3ehtyco99qrjor9devs437xk0cwer7em6p01l28ym19uufx/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>*@

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MobileGaget/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}